### ISSUE TITLE
Config file to specify excluded tables and table-level excluded columns

### ISSUE THREAD

**Issue by Supernats** [coverhound/fixturator#1]
Rather than specify columns as environment variable, I think it'd be nice to support this with a configuration file. This could be stored in version control and keep generation consistent. It would also deal with column name collisions for excludes, i.e. `foos.sensitive_column_name` should be excluded, but `bars.sensitive_column_name` should be included. We could have a global exclusions to cover the way it is current handled by environment variables.

Example:

```yaml
# .fixurator.yml

excluded_models:
  - Foo
  
global_exclusions:
  - ssn
  
model_level_exclusions:
  - Bar:
    - secret
    - sensitive
```
